---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: calumademo
  namespace: demo
  annotations:
    fluxcd.io/automated: "false"
    fluxcd.io/tag.chart-image: glob:3.1.1-debian-9-*
spec:
  releaseName: caluma
  chart:
    repository: https://charts.caluma.io
    name: caluma
    version: 0.7.0
